HWSTL-35 Create a C++ implementation of Myers's diff algorithm
wiebe-and-julian-engineering-co/bin-diff pull request #1
Opened 2018-11-09 16:54 UTC by JulianvDoorn

2018-11-09 16:58 UTC, JulianvDoorn commented on include/diff.hpp
>  class sequence_view {
Class should be moved into its own file

2018-11-09 16:58 UTC, JulianvDoorn commented on include/diff.hpp
>  class Patch {
Inconsistent class naming

2018-11-09 16:58 UTC, JulianvDoorn commented on include/diff.hpp
> +        void _diff(const sequence_view<t_sequenced_type>& lhs_seq, const sequence_view<t_sequenced_type>& rhs_seq, std::vector<Patch>& patches) {
Really long function, could be split into two

2018-11-12 11:51 UTC, JulianvDoorn commented on include/diff.hpp
>  class Patch {
A company-wide naming scheme should be setup

2018-11-15 10:25 UTC, BountyVSGames commented
You're sometimes not really consistent with where you end you scope. Like in this example you first close the previous if statement, and then you break off the line before the else if. While in the other cases you don't do that. It's not that bad if your the only person working on the project but if you have more then 1 programmer working on it, it could really piss people off.
![image](https://user-images.githubusercontent.com/19262437/48546414-98d50280-e8c8-11e8-8e33-9e87890f5cdd.png)

For the rest I don't really have anything to say about it, since I'm not that familiar with C++ yet.

2018-11-15 15:59 UTC, wvanbreukelen requested changes
Some small changes preferred.

2018-11-15 15:59 UTC, wvanbreukelen commented on include/diff.hpp
> +        int32_t max_len;
Length should always be unsigned, `uint32_t` is the better option here. Even better is to use `size_t`

2018-11-15 15:59 UTC, wvanbreukelen commented on include/patch.hpp
> +    patch(patch_operation op, size_t begin, std::string&& str) :
patch_operation and begin could be declared const

2018-11-15 15:59 UTC, wvanbreukelen commented on include/patch.hpp
> +    patch(patch_operation op, size_t begin, const std::string& str) :
Same here

2018-11-15 15:59 UTC, wvanbreukelen commented on include/sequence_view.hpp
> +        if (seq.m_seq != nullptr) {
I would write:

```cpp
if (seq.m_seq) {
  // Code...
} else {
  // os << "Null sequence";
}

2018-11-15 15:59 UTC, wvanbreukelen commented on src/main.cpp
> +    auto v = diff::diff(lhs, rhs);
Weird namespacing, I would rename it to ```diff::perform(lhs, rhs)```

2018-11-15 15:59 UTC, wvanbreukelen commented on src/main.cpp
> +    // system("pause");
Nitpicking: could be removed

2018-11-15 15:59 UTC, wvanbreukelen commented on src/main.cpp
> +    int i = 10;
Remove it

2018-11-15 16:00 UTC, JulianvDoorn commented on src/main.cpp
> +    // system("pause");
Should be removed*

2018-11-15 16:03 UTC, JulianvDoorn commented on src/main.cpp
> +    int i = 10;
Cleanup the main()

2018-11-16 10:27 UTC, JulianvDoorn commented on src/main.cpp
> +    auto v = diff::diff(lhs, rhs);
By writing diff::perform, the descriptive naming of the function "diff" is completely lost. What if someone performs `using namespace diff;`? Then obscure function calls to `perform(lhs, rhs)` will be all the way over...

2019-01-15 10:01 UTC, merged